### ISSUE TITLE
 Build issue: At least one invalid signature was encountered.

### ISSUE THREAD

**Issue by sk1me** [fazalfarhan01/EarnApp-Docker#1]
Hello, I have such error during build. Do you know what may be a cause? Invalid GPG signature?

Important info: I tried it on RaspberryPi.

> Step 6/15 : RUN apt-get update     && apt-get install -y --no-install-recommends     apt-utils locales python-setuptools python3-pip     software-properties-common rsyslog systemd systemd-cron     sudo iproute2     && apt install -y wget curl nano     dos2unix iputils-ping net-tools htop libatomic1     && rm -Rf /var/lib/apt/lists/*     && rm -Rf /usr/share/doc && rm -Rf /usr/share/man     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     && rm -f /lib/systemd/system/multi-user.target.wants/*     && rm -f /etc/systemd/system/*.wants/*     && rm -f /lib/systemd/system/local-fs.target.wants/*     && rm -f /lib/systemd/system/sockets.target.wants/*udev*     && rm -f /lib/systemd/system/sockets.target.wants/*initctl*     && rm -f /lib/systemd/system/basic.target.wants/*     && rm -f /lib/systemd/system/anaconda.target.wants/*     && rm -f /lib/systemd/system/plymouth*     && rm -f /lib/systemd/system/systemd-update-utmp*     && rm -Rf /usr/share/doc && rm -Rf /usr/share/man     && apt-get clean
 ---> Running in 904bbf271c2b
Get:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease [265 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Err:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  At least one invalid signature was encountered.
Err:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
  At least one invalid signature was encountered.
Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [108 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
Err:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
  At least one invalid signature was encountered.
Err:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports focal-security InRelease' is not signed.
The command '/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends     apt-utils locales python-setuptools python3-pip     software-properties-common rsyslog systemd systemd-cron     sudo iproute2     && apt install -y wget curl nano     dos2unix iputils-ping net-tools htop libatomic1     && rm -Rf /var/lib/apt/lists/*     && rm -Rf /usr/share/doc && rm -Rf /usr/share/man     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*     && rm -f /lib/systemd/system/multi-user.target.wants/*     && rm -f /etc/systemd/system/*.wants/*     && rm -f /lib/systemd/system/local-fs.target.wants/*     && rm -f /lib/systemd/system/sockets.target.wants/*udev*     && rm -f /lib/systemd/system/sockets.target.wants/*initctl*     && rm -f /lib/systemd/system/basic.target.wants/*     && rm -f /lib/systemd/system/anaconda.target.wants/*     && rm -f /lib/systemd/system/plymouth*     && rm -f /lib/systemd/system/systemd-update-utmp*     && rm -Rf /usr/share/doc && rm -Rf /usr/share/man     && apt-get clean' returned a non-zero code: 100
ERROR: Service 'app' failed to build

**Comment by sk1me** [comment]
It went through on Ubuntu. ;)

**Comment by fazalfarhan01** [comment]
@sk1me why did you want to build it though? The image is available on [docker hub](https://hub.docker.com/r/fazalfarhan01/earnapp) and it updates daily.

**Comment by sk1me** [comment]
@fazalfarhan01 I just ran docker-compose and it started to build the docker image.

Nice, I see there is also linux/arm/v7 version on the docker hub. Thank you!

**Comment by fazalfarhan01** [comment]
You are welcome. :)
