### ISSUE TITLE
Exited (255)

### ISSUE THREAD

**Issue by M1000fr** [fazalfarhan01/EarnApp-Docker#10]
I can't start the container,
i'm on debian 11, 
KVM, 
Docker version : 20.10.12
![WindowsTerminal_piTlTuldnO](https://user-images.githubusercontent.com/50182658/148767719-c7d40a22-cb56-4dac-b6b9-7b62d5bd323d.png)

**Comment by fazalfarhan01** [comment]
Try using the `debian` image tag.

**Comment by M1000fr** [comment]
Same thing.
![Image](https://files.m1000.fr/WindowsTerminal_DdT0LYHvAi.png)

**Comment by rtorrente** [comment]
Same here here on ubuntu 21.10 and docker 20.10.12
Exit 255 is instant without another log

Not data is added on ./etc

```
docker-compose up 
Starting earnapp ... done
Attaching to earnapp
earnapp exited with code 255
```

**Comment by fazalfarhan01** [comment]
The image seems to have issues with cgroups that's needed for systemd to work. The image works without any issues on **Ubuntu 20.04 LTS**.

**Comment by RoXuS** [comment]
same thing on docker arm64 with ubuntu.

**Comment by fazalfarhan01** [comment]
> same thing on docker arm64 with ubuntu.

Ubuntu 20.04? I have tested on it. And it works as expected. The problem is with other versions.

**Comment by RoXuS** [comment]
no, I am on 21.10 :(

**Comment by ejalal** [comment]
Same issue here, works OK on a Debian 10 host, but returns a 255 code on another Debian 11 host

**Comment by MASSKAgithub** [comment]
so not working as usual, ubuntu 22.04

**Comment by MASSKAgithub** [comment]
Works with 20.04

**Comment by kevin-soutar** [comment]
Having this issue on Ubuntu 20.04.3 LTS, but I was able to sping up 29 docker containers before, it seems to error out after 30, going to spin up another machine to test further
