### ISSUE TITLE
 EARNAPP_UUID

### ISSUE THREAD

**Issue by zeldhaking** [fazalfarhan01/EarnApp-Docker#11]
Hi, thx for your job!
I begin with EarnApp and i don't know where to find the EARNAPP_UUID for the lite version, can you help me?
Thx.

**Comment by fazalfarhan01** [comment]
Hi. [Mail me](mailto:fazal@ffehost.com) I'll send you the instructions or the UUID itself.

**Comment by victorelec14** [comment]
Could you share the steps to get the UUID? Thank you

**Comment by Tiebe** [comment]
@fazalfarhan01
