### ISSUE TITLE
won't start on synology docker DS718+ (Intel Celeron J3455)

### ISSUE THREAD

**Issue by jamieeyre** [fazalfarhan01/EarnApp-Docker#15]
I start the container with highest privileges, but it will not start.
I also created a volume under /etc/earnapp.

Here is the log output:

Welcome to Linux!
Set hostname to <fazalfarhan01-earnapp1>.
Cannot determine cgroup we are running in: No medium found
Failed to allocate manager object: No medium found
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
Failed to look up module alias 'autofs4': Function not implemented
systemd 245.4-4ubuntu3.15 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid)
Detected virtualization docker.
Detected architecture x86-64.
Failed to read os-release file, ignoring: No such device or address

**Comment by fazalfarhan01** [comment]
Synology doesn't allow cgroups to be accessed by any container. Even if the container is privileged. 

The only way to solve it is by using the _**lite**_ version of the container. That'll need a UUID. If you are running on windows as your default OS, download earnapp for windows. Install and when linking, it'll open a page with the UUID in the URL, **sdk-w8n-ehxuwjc**. Use this in place of UUID and you'll be good to go.

**Comment by grillead** [comment]
Hi, 
If you want to docker run in synology, you need to launch earnapp install in ssh.
Activate ssh in nas, login in with user/pass , launch install : docker run -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $HOME/earnapp-data:/etc/earnapp --name earnapp fazalfarhan01/earnapp
It run like charm in my DS420+

**Comment by jamieeyre** [comment]
@fazalfarhan01 

I tried the suggestion from @grillead 

I can confirm that this works!

Thanks @grillead 

N.B. To run the command from @grillead, you need to create a directory under $HOME/earnapp-data. This is where the earn app will store all it's data. To get the device ID, copy the value in the $HOME/earnapp-data/uuid file.

**Comment by fazalfarhan01** [comment]
Thanks for the update @jamieeyre and thanks for the solution @grillead.

**Comment by slhad** [comment]
> Hi, If you want to docker run in synology, you need to launch earnapp install in ssh. Activate ssh in nas, login in with user/pass , launch install : docker run -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $HOME/earnapp-data:/etc/earnapp --name earnapp fazalfarhan01/earnapp It run like charm in my DS420+

Does not work with a DS916+ with DSM 6 for info
