### ISSUE TITLE
Allow running lite container as non-root user

### ISSUE THREAD

**Issue by LuckyDams** [fazalfarhan01/EarnApp-Docker#20]
Currently it is not possible to run earnapp:lite with a specific user (other than root) such as in following command:
`docker run -d --user 1001 -e "EARNAPP_UUID=sdk-xyz" -v $HOME/etc:/etc/earnapp --name earnapp fazalfarhan01/earnapp:lite`

It will end with permission error due to following action requiring root privilege:
https://github.com/fazalfarhan01/EarnApp-Docker/blob/c33f2b9dd4e40b267db832687986080a8e290602/build/lite/src/install.sh#L13

Would it be possible to improve/fix this build by moving that line at end of [src/setup.sh](https://github.com/fazalfarhan01/EarnApp-Docker/blob/master/build/lite/src/setup.sh) script for example ?

**Comment by fazalfarhan01** [comment]
The lite version doesn't need to be run with root privileges. 
```bash
docker run -d -e "EARNAPP_UUID=sdk-xyz" --name earnapp fazalfarhan01/earnapp:lite
```
Use the snippet above, works like a charm.

**Comment by LuckyDams** [comment]
Let say I want to run this container with another uid than 0 (see [this](https://docs.docker.com/engine/reference/run/#user)).
This would allow having this container processes and files matching an existing user id on my host running docker. Mostly to match my user file permissions in mapped volume $HOME/etc (corresponding to /etc/earnapp in the container).

```
$ docker run -d --user 1001:100 -e "EARNAPP_UUID=sdk-xyz" -v /data/earnapp:/etc/earnapp --name earnapp fazalfarhan01/earnapp:lite

$ docker top earnapp -o uid,pid,cmd
UID                 PID                 CMD
1001                30041               /bin/bash /usr/bin/start
1001                30127               earnapp run

$ ls -nd /data/earnapp
drwxrwsrwx 1 1001 100 1486 Feb 22 12:58 /data/earnapp
```

**Comment by LuckyDams** [comment]
See [My-EarnApp-Lite](https://github.com/LuckyDams/My-EarnApp-Lite) as a possible implementation...
