### ISSUE TITLE
Container shows as running, however Earnapp console shows device is unavailable

### ISSUE THREAD

**Issue by jlegue** [fazalfarhan01/EarnApp-Docker#23]
I have noticed this happening a number of times over the past 4 days while running the container. Essentially the Earnapp console shows the device as offline and everything looks good in the docker UI. If I restart the docker image then refresh my Earnapp console it shows as online once more. Have you noticed any stability issues?

Environment:
Windows 10 Pro
Docker Desktop 4.5.1 (74721) running with WSL2 enabled

**Comment by fazalfarhan01** [comment]
Hi @jlegue 
This is an issue being addressed from earnapp. They have had an announcement lately about it on discord server.

More info about it [here](https://discord.com/channels/894120260846891008/942075043817615422/949391047572742196)
