### ISSUE TITLE
Link device button don't exist

### ISSUE THREAD

**Issue by abneits** [fazalfarhan01/EarnApp-Docker#25]
seems that link device button doesn't exist anymore on the dashboard,

Instead, in FAQ, they say that we have to click on generating url after installation,

How can we have access to this url in ur image?

**Comment by xplodwild** [comment]
Use `docker exec -it earnapp earnapp register`

**Comment by fazalfarhan01** [comment]
Hi @abneits 
The URL to link your device will be `https://earnapp.com/r/sdk-node-something_random`

You can access the same by running the command `earnapp register` inside the container.

**Comment by abneits** [comment]
Thx guys,

it works like a charm,

**Comment by fazalfarhan01** [comment]
> it works like a charm

Peace
