### ISSUE TITLE
don't work on Raspberry PI 3 ?

### ISSUE THREAD

**Issue by moebius911** [fazalfarhan01/EarnApp-Docker#26]
Hello
I use the fazalfarhan01/earnapp:lite version on Docker with a Rapsberry PI 3.
Unfortunately the ShowID command does not show me anything.
Here is the output on my command prompt:

pi@Chalet:~ $ docker exec -it earnapp_Lite earnapp status
✔ Current status: enabled
pi@Chalet:~ $ docker exec -it earnapp_Lite earnapp showid

pi@Chalet:~ $

has anyone managed to get it to work on Rapsberry Pi 3?
thank you in advance

**Comment by fazalfarhan01** [comment]
The `lite` version requires you to provide a UUID. It can't generate one on its own. 

And yes, `lite` version works on anything and everything.

**Comment by moebius911** [comment]
thank you for such a quick response.
As you point out to me, I can see that the $Home/earnapp-data/uuid file is empty.
My question may be stupid but how can I generate an sdk-node?
I'm used to them generating themselves...
thanks

**Comment by moebius911** [comment]
in the end, I launch an installation of earnapp, I recover the sdk, I uninstall and I reinstall for a new sdk.
If there are people like me who are not familiar with docker, I recommend the following command to install the container directly with the correct SDK :
docker run -d --privileged -v  /sys/fs/cgroup:/sys/fs/cgroup:ro -v $HOME/earnapp-data:/etc/earnapp -e EARNAPP_UUID='sdk-node-XXXXXXXXXXXXXXXXXXX' --name earnapp_lite fazalfarhan01/earnapp:lite
Thank you fazalfarhan01 for showing me my error
bye

**Comment by moebius911** [comment]
in the end, I launch an installation of earnapp, I recover the sdk, I uninstall and I reinstall for a new sdk.
If there are people like me who are not familiar with docker, I recommend the following command to install the container directly with the correct SDK :
docker run -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v $HOME/earnapp-data:/etc/earnapp -e EARNAPP_UUID='sdk-node-XXXXXXXXXXXXXXXXXXX' --name earnapp_lite fazalfarhan01/earnapp:lite
Thank you fazalfarhan01 for showing me my error
bye

**Comment by fazalfarhan01** [comment]
@moebius911 Glad it worked out..
