### ISSUE TITLE
Connection lost / "EarnApp was already started before."

### ISSUE THREAD

**Issue by BruceFeuillette** [fazalfarhan01/EarnApp-Docker#27]
Hello,
Since 29th march, I guess just after the new image was pulled, I've lost the connection with Earnapp.
If I stop and start my container, it says "EarnApp was already started before."
Could this be the reason for my dockers to be offline on the EarnApp's dashboard ?
Just to be sure, I've just checked with a new ID, straight from my Windows laptop and it's good on the dashboard.
So I created a new docker with this new ID. But it don't show as connected on the dashboard.

**Comment by fazalfarhan01** [comment]
Are you using the lite version? I have noticed a glitch where in the command `earnapp start` doesn't exit and stays for ever. If you are using the `lite` image, I have just updated it. Try pulling a new image and give it a go. That should work.

**Comment by BruceFeuillette** [comment]
Yes, it's the `lite`, one, sorry to forget to mention!
It's better, all is running fine, except the fact that the dockers won't show as connected...
I tried an "old" UUID and a new one, that was fine on my laptop there's 15 minutes, just to confirm that my IP has not been blacklisted by EarnApp.
Is there a mean to verify that my docker is communicating well with the EarnApp's servers ?

**Comment by fazalfarhan01** [comment]
> Is there a mean to verify that my docker is communicating well with the EarnApp's servers ?

Yes. Check the logs and see if there are multiple Connection Refused. If no.. then you are fine..

**Comment by BruceFeuillette** [comment]
Everything looks fine, either on the container log (on Synology DSM) or in the /var/log of the container.
It looks like my containers have been blocked, but not the client on my computer. Really strange. I'll get in touch with the EarnApp support then. :)

**Comment by BruceFeuillette** [comment]
It's all fine by now. It looks like it was solved by an update yesterday evening. The image was updated and it started to work again.
In a side note, I sent an email to the support to open a ticket. I don't know if the two are linked.

**Comment by fazalfarhan01** [comment]
> In a side note, I sent an email to the support to open a ticket. I don't know if the two are linked.

If you happen to mention **docker**. Don't expect a reply. They just don't provide support for anything on docker even though it's their own application. 🥲

**Comment by BruceFeuillette** [comment]
No, no, I just mentioned "4 Debian VM"... 😅
