### ISSUE TITLE
docker image on wsl2

### ISSUE THREAD

**Issue by MrAuronTV** [fazalfarhan01/EarnApp-Docker#5]
Hello

Can we run earnapp docker image on WSL2 ?
i try but my container doesnt start

Regards

**Comment by fazalfarhan01** [comment]
WSL2 is incompatible with systemd cgroup.
You can use the lite version on WSL

**Comment by MrAuronTV** [comment]
Ok thanks !

**Comment by MrAuronTV** [comment]
how to get uuid on wsl2 ?

**Comment by fazalfarhan01** [comment]
> how to get uuid on wsl2 ?

[Duplicate](https://github.com/fazalfarhan01/EarnApp-Docker/issues/3)
Check this for more info.
