### ISSUE TITLE
arm version

### ISSUE THREAD

**Issue by Kawabountou** [fazalfarhan01/EarnApp-Docker#6]
Hi and thanks for your job.

Your docker work fine on amd64.

Moreover, is it possible to convert your docker for arm architecture? (like RPi0).

Thanks in advance for your replie.

**Comment by fazalfarhan01** [comment]
Hey. The previous version of RPI0 is an arm V6, I had tried building an image for arm V6 and unfortunately the build failed. There's an armv7 version available, any pi above the 3B version will work with that.

**Comment by Kawabountou** [comment]
OK, thanks for your replie.

for information, earnapp work on arm v6
https://www.maison-et-domotique.com/133514-earnapp-gagner-15-dollars-par-mois-grace-au-raspberrypi/  (in french^^)

so, i will check what's wrong

**Comment by fazalfarhan01** [comment]
Yep. Earnapp works on armv6, but i haven't been able to build an image for docker on armv6. That's the issue here.. 🥲

**Comment by Kawabountou** [comment]
i have found some information

ubuntu 20.04 is not fullfully compatible arm v6

when i switch between ubuntu and debian:stretch (wich is totaly compatible), the building and the docker works fine.

Moreover, i have a last problem because files are not copied to the bolder inside the docker

**Comment by fazalfarhan01** [comment]
Can you list the files which aren't being copied? Well actually there's no reason for that. Let me know if there's any particular error during the build or during install

**Comment by Kawabountou** [comment]
sry, i forget to read this line RUN bash /app/src/setup.sh && rm -r /app/src
so it's normal

i continue to investigate the problem, and when i enter in the docker, earnapp doesn't exist
/usr/bin/earnapp: No such file or directory

i think that there is a problem during the installation

**Comment by fazalfarhan01** [comment]
Cool... Submit a PR if you find the solution. 

And earnapp is downloaded in the `/downloads` directory.
The install script copies it to cwd and then runs the `earnapp install` command

**Comment by Kawabountou** [comment]
have you a discord for tchating. I don't find the solution

**Comment by fazalfarhan01** [comment]
Yep.. @toothyraider201#4454
